# Configuration Owncast

# Clés de stream (c'est ce que tu mets dans OBS)
streamKeys:
  - key: "symphorlive"
    user: "admin"
    comment: "Clé principale de diffusion"

# Informations sur l’instance
instanceDetails:
  name: "Symphor HD TV"
  title: "Chaîne indépendante en direct"
  summary: "Bienvenue sur Symphor HD TV en direct 24/7."
  logo:
  tags: ["live", "tv", "indépendant"]

# Paramètres vidéo
videoSettings:
  videoQualityVariants:
    - name: "720p"
      videoBitrate: 1500
      audioBitrate: 128
      scaledWidth: 1280
      scaledHeight: 720
      framerate: 30

# Paramètres HTTP
webServer:
  port: 8080
  publicHost: "shdtv.onrender.com"

# Utilisateur admin pour l’interface
admin:
  username: "admin"
  password: "Bksymphor0085@"

# Stockage des données
storage:
  enabled: true
  directory: "/app/data"

# Limite de connexion
maxNumberOfViewers: 500

# Logs
logging:
  level: "info"
